# 1. Configuracion de la conexion a PostgreSQL
# Cambia el nombre de la base al final por zonarefri_db (o el que uses en Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/zonaRefri
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto especifico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Configuracion del servidor (Opcional)
server.port=8080

# Evita que la conexion a la BD se mantenga abierta innecesariamente
# spring.jpa.open-in-view=false

# Opcional: Para que no veas el mensaje de advertencia en consola
# logging.level.org.springframework.orm.jpa=ERROR