# 1. Configuración de la conexión a PostgreSQL
# El puerto por defecto de Postgres es 5432
spring.datasource.url=jdbc:postgresql://dpg-d6pgbftactks73epfkl0-a.oregon-postgres.render.com:5432/zonarefri_db_gi

spring.datasource.username=zonarefri_db_gi_user

# IMPORTANTE: Cambia 'tu_contraseña' por la que usas en pgAdmin
spring.datasource.password=GOFMOX8fLoQiUhJlPiUS12UbY0IVUuXu
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# 'update' creará las tablas en Postgres basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# 3. Configuración del servidor
server.port=8080

# Recomendado para evitar problemas de rendimiento en aplicaciones grandes
spring.jpa.open-in-view=false